### PR TITLE
Feature/allow default sizing

### PR DESCRIPTION
**Pull request by kitbrennan90**
Allows a user to override the default height or width by passing in youtubeHeight or youtubeWidth into the showdown settings.

Includes test cases.

**NOTE**: we haven't compiled a dist of this or our other pull request (given they would just conflict if we submitted both at once). Ping me a message if both are merged and I'd be happy to submit a compiled pull request.

### CODE REVIEW

**Comment by kitbrennan90** [comment]
Apologies, I'll fix the conflict quickly...

**Comment by kitbrennan90** [comment]
@tivie thanks for merging and releasing the other pull request so quickly.  Sorry for not leaving a comment that I'd be submitting two - didn't mean to duplicate your hard work!

**Comment by tivie** [comment]
Wait... building is failing.

**Comment by tivie** [comment]
fixed it in develop branch

**Comment by SyntaxRules** [comment]
@tivie, Thanks for fixing that. I saw that the checks passed for the pull request and assumed that was the build passing. My mistake!

**Pull request merged**
