### PR TITLE
Allow enablejsapi as an option for YouTube

### LINKED ISSUE #11: Feature Request: Allow adding `&enablejsapi=1` to YouTube Url
Would like to have an option to append `&enablejsapi=1` to the YouTube URLs to allow for JS control of YouTube videos embedded via this extension.

### PR DESCRIPTION
**Pull request by cfurrow**
Fixes #11

### CODE REVIEW

**Comment by cfurrow** [comment]
Unclear why the travis builds are failing for the other node versions. I could not rebuild the job without making a new commit, I reckon. Thoughts?

**Comment by tivie** [comment]
Seems I need to update travis definitions.

**Comment by SyntaxRules** [comment]
Working on fixing the build system in #13

**Comment by cfurrow** [comment]
Awesome, thanks!

**Pull request merged**
